# Generated by Django 4.2.23 on 2025-08-31 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(editable=False, max_length=5, null=True, unique=True),
        ),
    ]
